### ISSUE TITLE
New release for  VegaLite 1.0 compatibility?

### ISSUE THREAD

**Issue by tkf** [queryverse/DataVoyager.jl#23]
Thanks to 4fbc7bcc6edd34c02fe9e3626bd21ed9f4b66951 DataVoyager works with VegaLite 1.0 if I `dev` it.  Can this be released as-is?

PS: Thanks for VegaLite 1.0 release! :tada:

**Comment by davidanthoff** [comment]
I'm just waiting for someone to merge https://github.com/JuliaRegistries/General/pull/5642, which should take care of this.

**Comment by tkf** [comment]
Ah, I should've searched the registry PR. Thanks!
