### ISSUE TITLE
"GtkDialog mapped without a transient parent. This is discouraged"

### ISSUE THREAD

**Issue by bradlindblad** [queryverse/DataVoyager.jl#34]
I'm trying to create a simple CLI program to pass a csv to Voyager, like this:

```
julia  myVoyager.jl  /path/to/local.csv
```
myVoyager.jl is something simple like this:
```
df = DataFrame(CSV.read(string(ARGS[1])))
Voyager(df)
```

When I pull up a dataframe in a REPL or in VS Code, it works fine, but when I try to run this as a CLI program, I get the error: "GtkDialog mapped without a transient parent. This is discouraged", and the window doesn't open.

Ideas?

**Comment by davidanthoff** [comment]
Hm, presumably you need to make sure the Julia script you have doesn't quit after those two lines. The voyager window won't stop the Julia script from closing. So maybe a simple `readline()` at the end might to the trick.

**Comment by bradlindblad** [comment]
Ahh, of course. That worked, thanks!
