### ISSUE TITLE
libgobject-2.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by tk3369** [queryverse/DataVoyager.jl#38]
I just installed DataVoyager 1.0.0 but it's giving me an error:

```
julia> using DataVoyager
[ Info: Precompiling DataVoyager [5721bf48-af8e-5845-8445-c9e18126e773]

julia> v = Voyager()
/home/tkwong/.julia/artifacts/41afcbdbe95343621162214b9fc07813c12b5d36/electron: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```

Nothing comes up and the call isn't returning...  

My version:
```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by davidanthoff** [comment]
My best guess is that you need to install some more stuff so that electronjs can work on your system with your OS package manager. Something like `sudo apt install libglib2.0-0`.

**Comment by tk3369** [comment]
Ah... never mind.  I am used to running Julia on a remote server, and this would have never worked anyways 😝 OK to close this issue.
